server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauldZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: IMMIGRATION-INFORMATION-SERVICE